import { KpiMetric, RevenueForecastPoint, AiAlert, NetworkNode } from '../types';

export const mockKpis: KpiMetric[] = [
  {
    title: 'Annual Run Rate (ARR)',
    value: '$1,280,450',
    subValue: '+$142.3k this month',
    change: '+18.4%',
    isPositive: true,
    period: 'vs last quarter',
    iconName: 'DollarSign',
    accentColor: 'purple',
  },
  {
    title: 'Active Customers',
    value: '4,892',
    subValue: '+328 new accounts',
    change: '+12.6%',
    isPositive: true,
    period: 'vs last month',
    iconName: 'Users',
    accentColor: 'orange',
  },
  {
    title: 'Monthly Spend',
    value: '$84,210',
    subValue: 'Budget: $95,000',
    change: '-3.2%',
    isPositive: true,
    period: 'under allocation',
    iconName: 'CreditCard',
    accentColor: 'emerald',
  },
  {
    title: 'Net Profit Margin',
    value: '42.8%',
    subValue: 'Total net: $548.1k',
    change: '+6.1%',
    isPositive: true,
    period: 'vs target 38%',
    iconName: 'TrendingUp',
    accentColor: 'purple',
  },
];

export const mockRevenueForecast: RevenueForecastPoint[] = [
  { month: 'Jan', actual: 65000, predicted: 62000, baseline: 55000 },
  { month: 'Feb', actual: 72000, predicted: 70000, baseline: 58000 },
  { month: 'Mar', actual: 80000, predicted: 79000, baseline: 62000 },
  { month: 'Apr', actual: 89000, predicted: 86000, baseline: 65000 },
  { month: 'May', actual: 98000, predicted: 95000, baseline: 70000 },
  { month: 'Jun', actual: 112000, predicted: 108000, baseline: 75000 },
  { month: 'Jul', actual: 124000, predicted: 121000, baseline: 80000 },
  { month: 'Aug', actual: 135000, predicted: 132000, baseline: 85000 },
  { month: 'Sep', actual: 149000, predicted: 145000, baseline: 90000 },
  { month: 'Oct', actual: 162000, predicted: 160000, baseline: 95000 },
  { month: 'Nov', actual: 178000, predicted: 174000, baseline: 100000 },
  { month: 'Dec', actual: 198000, predicted: 192000, baseline: 105000 },
];

export const mockAiAlerts: AiAlert[] = [
  {
    id: 'alt-1',
    type: 'opportunity',
    title: 'NVDA Arbitrage Spread',
    description: 'Autonomous cluster detected 2.4% valuation divergence across Nasdaq and OTC derivatives.',
    confidence: 96,
    timestamp: '2m ago',
    symbol: 'NVDA',
    impact: 'high',
  },
  {
    id: 'alt-2',
    type: 'rebalance',
    title: 'Alpha Portfolio Drift',
    description: 'Tech sector weighting exceeded 45% ceiling. Rebalancing trigger ready for confirmation.',
    confidence: 92,
    timestamp: '14m ago',
    symbol: 'PORT-1',
    impact: 'medium',
  },
  {
    id: 'alt-3',
    type: 'risk',
    title: 'Fed Rate Volatility Flag',
    description: 'Macro sentiment scraper indicates elevated tail-risk ahead of FOMC policy minutes release.',
    confidence: 88,
    timestamp: '45m ago',
    impact: 'high',
  },
  {
    id: 'alt-4',
    type: 'anomaly',
    title: 'Unusual Volume in TSLA OTM Calls',
    description: 'Abnormal block purchase of 18,500 weekly strike calls detected across dark pool liquidity feeds.',
    confidence: 94,
    timestamp: '1h ago',
    symbol: 'TSLA',
    impact: 'medium',
  },
];

export const mockNetworkNodes: NetworkNode[] = [
  {
    id: 'node-alpha-1',
    name: 'Macro Quant Sentinel Agent',
    type: 'Transformer Agent',
    status: 'Active',
    latency: '12ms',
    throughput: '42.8k msgs/s',
    accuracy: '99.4%',
    lastUpdated: 'Just now',
  },
  {
    id: 'node-sec-feed',
    name: 'SEC Edgar 10-K RAG Pipeline',
    type: 'Vector Indexer',
    status: 'Active',
    latency: '34ms',
    throughput: '12.4 docs/s',
    accuracy: '98.8%',
    lastUpdated: '1m ago',
  },
  {
    id: 'node-order-hedge',
    name: 'Smart Order Router & Hedge',
    type: 'Execution Gateway',
    status: 'Optimizing',
    latency: '8ms',
    throughput: '890 tx/s',
    accuracy: '99.9%',
    lastUpdated: '3m ago',
  },
  {
    id: 'node-sentiment-v2',
    name: 'Real-Time News NLP Cluster',
    type: 'Sentiment Classifier',
    status: 'Active',
    latency: '19ms',
    throughput: '5.2k feeds/m',
    accuracy: '96.5%',
    lastUpdated: '4m ago',
  },
  {
    id: 'node-crypto-arb',
    name: 'DeFi & Spot Cross-Exchange Arb',
    type: 'Multi-Leg Router',
    status: 'Standby',
    latency: '45ms',
    throughput: '340 tx/s',
    accuracy: '97.2%',
    lastUpdated: '12m ago',
  },
];
