"""phase3_intelligence_history

Revision ID: 7e0c63526b4c
Revises: 8bd80ef2a060
Create Date: 2026-09-01 13:54:31.497341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e0c63526b4c'
down_revision: Union[str, None] = '8bd80ef2a060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('analysis_type', sa.String(length=50), nullable=True),
    sa.Column('overall_assessment', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('recommendation_json', sa.Text(), nullable=False),
    sa.Column('agents_consulted_json', sa.Text(), nullable=False),
    sa.Column('findings_json', sa.Text(), nullable=False),
    sa.Column('conflicts_json', sa.Text(), nullable=False),
    sa.Column('reasoning_trace_json', sa.Text(), nullable=False),
    sa.Column('sources_json', sa.Text(), nullable=False),
    sa.Column('execution_time_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_history_id'), 'analysis_history', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_history_request_id'), 'analysis_history', ['request_id'], unique=True)
    op.create_index(op.f('ix_analysis_history_symbol'), 'analysis_history', ['symbol'], unique=False)
    op.create_index('ix_analysis_user_symbol', 'analysis_history', ['user_id', 'symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analysis_user_symbol', table_name='analysis_history')
    op.drop_index(op.f('ix_analysis_history_symbol'), table_name='analysis_history')
    op.drop_index(op.f('ix_analysis_history_request_id'), table_name='analysis_history')
    op.drop_index(op.f('ix_analysis_history_id'), table_name='analysis_history')
    op.drop_table('analysis_history')
    # ### end Alembic commands ###
