"""add_raw_content_to_documents

Revision ID: 8bd80ef2a060
Revises: 74c45f131c8a
Create Date: 2026-09-01 13:49:33.245293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bd80ef2a060'
down_revision: Union[str, None] = '74c45f131c8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('raw_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'raw_content')
    # ### end Alembic commands ###
